
<?php
$form = $this->form;
$result=$this->result;
$form->prepare();
// Assuming the "contact/process" route exists...
$form->setAttribute('action', $this->url('home', array('controller' => 'index', 'action' => 'index'))); //'contact/process'));
// Set the method attribute for the form
$form->setAttribute('method', 'post');
?>
<div class="row">
<div class="col-md-8 col-md-push-3" >
<?php
echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();
?>

</div>
</div>
